#include "../include/BST.h"
#include <iostream>


// ==================================================
// COMMENTS GENERATED BY IA SEEKING ORDER AND AGILITY
// ==================================================
// Constructor
// ==================================================
// Creates an empty Binary Search Tree.
//
// Initially:
//
// root
//  |
// nullptr
// ==================================================

BST::BST()
{
    root = nullptr;
}

// ==================================================
// Recursive insertion
// ==================================================
//
// Inserts a new asteroid into the BST.
//
// Rule:
// Smaller values go left.
// Greater or equal values go right.
//
// Example:
//
// Insert 100
//
//      100
//
// Insert 50
//
//      100
//      /
//    50
//
// Insert 150
//
//      100
//      /  \
//    50   150
//
// ==================================================

BSTNode* BST::insertNode(
    BSTNode* node,
    const std::string& name,
    int value
)
{
    // Empty position found:
    // create a new node.
    if(node == nullptr)
    {
        return new BSTNode(
            name,
            value
        );
    }

    // Smaller values go to the left subtree
    if(value < node->value)
    {
        node->left =
            insertNode(
                node->left,
                name,
                value
            );
    }
    else
    {
        // Greater or equal values go right
        node->right =
            insertNode(
                node->right,
                name,
                value
            );
    }

    return node;
}

// ==================================================
// Public insertion method
// ==================================================
//
// Starts recursive insertion from the root.
//
// ==================================================

void BST::insert(
    const std::string& name,
    int value
)
{
    root =
        insertNode(
            root,
            name,
            value
        );
}

// ==================================================
// Recursive inorder traversal
// ==================================================
//
// Traversal order:
//
// Left -> Root -> Right
//
// This automatically prints the asteroid catalog
// sorted by value.
//
// Example tree:
//
//         100
//        /   \
//      50    150
//
// Output:
//
// 50
// 100
// 150
//
// ==================================================

void BST::inorderNode(
    BSTNode* node
)
{
    // Base case:
    // stop when reaching an empty branch.
    if(node == nullptr)
        return;

    // Visit left subtree
    inorderNode(node->left);

    // Process current node
    std::cout
        << node->name
        << " "
        << node->value
        << std::endl;

    // Visit right subtree
    inorderNode(node->right);
}

// ==================================================
// Public inorder method
// ==================================================
//
// Starts traversal from the root.
//
// ==================================================

void BST::inorder()
{
    inorderNode(root);
}