#include "../include/LinkedList.h"
#include <fstream>
#include <iostream>


// ==================================================
// COMMENTS GENERATED BY IA SEEKING ORDER AND AGILITY
// ==================================================
// Constructor
// ==================================================
// Creates an empty linked list.
// Initially there are no nodes.
// ==================================================

LinkedList::LinkedList()
{
    head = nullptr;
}

// ==================================================
// Insert a new route at the end of the list
// ==================================================
//
// Example:
//
// Before:
// head -> Route1 -> Route2
//
// After insert(Route3):
// head -> Route1 -> Route2 -> Route3
//
// ==================================================

void LinkedList::insert(
    const std::string& route
)
{
    // Create a new node dynamically
    Node* newNode =
        new Node(route);

    // If the list is empty,
    // the new node becomes the head.
    if(head == nullptr)
    {
        head = newNode;
        return;
    }

    // Traverse to the last node
    Node* current = head;

    while(current->next != nullptr)
    {
        current = current->next;
    }

    // Attach the new node
    current->next = newNode;
}

// ==================================================
// Print all stored routes
// ==================================================
//
// Traverses the entire list from head to tail.
//
// Example output:
//
// S1->G1->D1
// G2->D2
// DM1->S2
//
// ==================================================

void LinkedList::print()
{
    Node* current = head;

    while(current != nullptr)
    {
        std::cout
            << current->route
            << std::endl;

        current = current->next;
    }
}

// ==================================================
// Destructor
// ==================================================
//
// Frees all dynamically allocated nodes.
//
// This prevents memory leaks when the
// LinkedList object is destroyed.
//
// ==================================================

LinkedList::~LinkedList()
{
    Node* current = head;

    while(current != nullptr)
    {
        Node* temp = current;

        current = current->next;

        delete temp;
    }
}

// ==================================================
// Save entire route history to file
// ==================================================
//
// Appends all routes currently stored in the list.
//
// Example:
//
// Level 1 | Resources 450 | Stars 3 | S1->G1
// Level 2 | Resources 600 | Stars 2 | D1->G2
//
// ==================================================

void LinkedList::saveToFile(
    const std::string& filename
)
{
    std::ofstream file(
        filename,
        std::ios::app
    );

    Node* current = head;

    while(current)
    {
        file
            << current->route
            << std::endl;

        current = current->next;
    }

    file.close();
}

// ==================================================
// Append routes to an existing file
// ==================================================
//
// Similar to saveToFile().
// Writes each route at the end of the file.
//
// ==================================================

void LinkedList::appendToFile(
    const std::string& filename
)
{
    std::ofstream file(
        filename,
        std::ios::app
    );

    Node* current = head;

    while(current != nullptr)
    {
        file
            << current->route
            << std::endl;

        current = current->next;
    }

    file.close();
}