#include "include/LinkedList.h"
#include "include/BST.h"

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

int main()
{
    // ==================================================
    // COMMENTS GENERATED BY IA SEEKING ORDER AND AGILITY
    // ==================================================
    // LOAD GAME DATA GENERATED BY PYTHON
    // ==================================================
    // The game stores the mission results in a JSON file.
    // This C++ module reads that file to process routes
    // and asteroid information using data structures.
    // ==================================================

    std::ifstream file(
        "data/game_state.json"
    );

    if(!file.is_open())
    {
        std::cout
            << "Cannot open game_state.json"
            << std::endl;

        return 1;
    }

    // Read the entire file into a string
    std::stringstream buffer;
    buffer << file.rdbuf();

    std::string json = buffer.str();

    file.close();

    // ==================================================
    // REMOVE WHITESPACES
    // ==================================================
    // Since we are not using a JSON library, removing
    // spaces and line breaks simplifies string parsing.
    // ==================================================

    std::string compact;

    for(char c : json)
    {
        if(
            c != ' ' &&
            c != '\n' &&
            c != '\t' &&
            c != '\r'
        )
        {
            compact += c;
        }
    }

    json = compact;

    // ==================================================
    // EXTRACT GENERAL GAME INFORMATION
    // ==================================================
    // Read:
    // - Level completed
    // - Resources collected
    // - Stars obtained
    // ==================================================

    int level = 0;
    int resources = 0;
    int stars = 0;

    // ---------- LEVEL ----------
    size_t levelPos =
        json.find("\"level\":");

    if(levelPos != std::string::npos)
    {
        levelPos += 8;

        size_t end =
            json.find(
                ",",
                levelPos
            );

        level =
            std::stoi(
                json.substr(
                    levelPos,
                    end - levelPos
                )
            );
    }

    // ---------- RESOURCES ----------
    size_t resourcesPos =
        json.find("\"resources\":");

    if(resourcesPos != std::string::npos)
    {
        resourcesPos += 12;

        size_t end =
            json.find(
                ",",
                resourcesPos
            );

        resources =
            std::stoi(
                json.substr(
                    resourcesPos,
                    end - resourcesPos
                )
            );
    }

    // ---------- STARS ----------
    size_t starsPos =
        json.find("\"stars\":");

    if(starsPos != std::string::npos)
    {
        starsPos += 8;

        size_t end =
            json.find(
                ",",
                starsPos
            );

        stars =
            std::stoi(
                json.substr(
                    starsPos,
                    end - starsPos
                )
            );
    }

    // ==================================================
    // CREATE DATA STRUCTURES
    // ==================================================
    // Linked List:
    //     Stores route history.
    //
    // Binary Search Tree:
    //     Stores asteroid catalog ordered by value.
    // ==================================================

    LinkedList history;
    BST catalog;

    std::string route_string;

    // ==================================================
    // BUILD ASTEROID CATALOG (BST)
    // ==================================================
    // Every asteroid stored in the JSON file is inserted
    // into the BST using its resource value as the key.
    //
    // This allows ordered traversal and demonstrates
    // efficient insertion/search operations.
    // ==================================================

    size_t catalogPos = 0;

    while(
        (
            catalogPos =
            json.find(
                "\"name\":\"",
                catalogPos
            )
        )
        != std::string::npos
    )
    {
        catalogPos += 8;

        size_t end =
            json.find(
                "\"",
                catalogPos
            );

        std::string asteroidName =
            json.substr(
                catalogPos,
                end - catalogPos
            );

        size_t valuePos =
            json.find(
                "\"value\":",
                end
            );

        valuePos += 8;

        size_t valueEnd =
            json.find_first_of(
                ",}",
                valuePos
            );

        int asteroidValue =
            std::stoi(
                json.substr(
                    valuePos,
                    valueEnd - valuePos
                )
            );

        catalog.insert(
            asteroidName,
            asteroidValue
        );

        catalogPos = end;
    }

    // ==================================================
    // REBUILD PLAYER ROUTE
    // ==================================================
    // Extract asteroid names and create a readable route
    // string such as:
    //
    // S1->G1->D1->DM1
    // ==================================================

    size_t pos = 0;

    while(
        (
            pos =
            json.find(
                "\"name\":\"",
                pos
            )
        )
        != std::string::npos
    )
    {
        pos += 8;

        size_t end =
            json.find(
                "\"",
                pos
            );

        std::string asteroid =
            json.substr(
                pos,
                end - pos
            );

        if(!route_string.empty())
        {
            route_string += "->";
        }

        route_string += asteroid;

        pos = end;
    }

    // ==================================================
    // CREATE MISSION HISTORY ENTRY
    // ==================================================
    // Example:
    //
    // Level 2 | Resources 450 | Stars 3 | S1->G1->D1
    //
    // This information is stored in the Linked List and
    // later appended to the history file.
    // ==================================================

    std::string history_entry =
        "Level " +
        std::to_string(level) +
        " | Resources " +
        std::to_string(resources) +
        " | Stars " +
        std::to_string(stars) +
        " | " +
        route_string;

    history.insert(
        history_entry
    );

    history.appendToFile(
        "data/route_history.txt"
    );

    // ==================================================
    // DISPLAY GAME SUMMARY
    // ==================================================

    std::cout
        << "\nGAME SUMMARY\n"
        << std::endl;

    std::cout
        << "Level: "
        << level
        << std::endl;

    std::cout
        << "Resources: "
        << resources
        << std::endl;

    std::cout
        << "Stars: "
        << stars
        << std::endl;

    // ==================================================
    // DISPLAY LINKED LIST CONTENT
    // ==================================================
    // Prints the latest mission stored in memory.
    // ==================================================

    std::cout
        << "\nROUTE HISTORY\n"
        << std::endl;

    history.print();

    // ==================================================
    // DISPLAY BST CONTENT
    // ==================================================
    // In-order traversal prints asteroids sorted
    // by value from lowest to highest.
    // ==================================================

    std::cout
        << "\nASTEROID CATALOG\n"
        << std::endl;

    catalog.inorder();

    // ==================================================
    // GENERATE OUTPUT FILE FOR PYTHON
    // ==================================================
    // Sends processed information back to Python.
    // The game can later display the saved route and
    // mission statistics.
    // ==================================================

    std::ofstream output(
        "data/output.json"
    );

    output
        << "{\n"
        << "\"status\":\"ok\",\n"
        << "\"level\":"
        << level
        << ",\n"
        << "\"resources\":"
        << resources
        << ",\n"
        << "\"stars\":"
        << stars
        << ",\n"
        << "\"route_saved\":\""
        << route_string
        << "\"\n"
        << "}";

    output.close();

    return 0;
}