#ifndef BST_H
#define BST_H

#include <string>


// ==================================================
// COMMENTS GENERATED BY IA SEEKING ORDER AND AGILITY
// ==================================================
// Binary Search Tree Node
// ==================================================
// Each node stores:
// - asteroid name
// - asteroid value
// - left child
// - right child
//
// Example:
//
//         Gold
//        /    \
//    Silver   Diamond
//
// ==================================================

struct BSTNode
{
    // Asteroid identifier
    std::string name;

    // Resource value
    int value;

    // Child pointers
    BSTNode* left;
    BSTNode* right;

    // Node constructor
    BSTNode(const std::string& n, int v)
    {
        name = n;
        value = v;

        left = nullptr;
        right = nullptr;
    }
};

// ==================================================
// Binary Search Tree
// ==================================================
// Stores asteroid information in sorted order.
//
// Main operations:
// - Insert asteroid
// - Traverse tree in-order
//
// Used to generate the Asteroid Catalog shown
// after each mission.
// ==================================================

class BST
{
private:

    // Root node of the tree
    BSTNode* root;

    // Recursive insertion helper
    BSTNode* insertNode(
        BSTNode* node,
        const std::string& name,
        int value
    );

    // Recursive in-order traversal helper
    void inorderNode(
        BSTNode* node
    );

public:

    // Create empty tree
    BST();

    // Insert asteroid into the BST
    void insert(
        const std::string& name,
        int value
    );

    // Print asteroids in sorted order
    void inorder();
};

#endif