#ifndef LINKEDLIST_H
#define LINKEDLIST_H

#include <string>


// ==================================================
// COMMENTS GENERATED BY IA SEEKING ORDER AND AGILITY
// ==================================================
// Node structure
// ==================================================
// Each node stores one route and a pointer
// to the next node in the list.
// ==================================================

struct Node
{
    // Route generated by the player
    std::string route;

    // Pointer to the next node
    Node* next;

    // Node constructor
    Node(const std::string& r)
    {
        route = r;
        next = nullptr;
    }
};

// ==================================================
// Linked List class
// ==================================================
// Stores route history using dynamic memory.
// Each route is saved as a node.
//
// Example:
//
// S1->G1->D1
//       |
//       v
// G2->DM1
//       |
//       v
// S2->G3
// ==================================================

class LinkedList
{
private:

    // First node of the list
    Node* head;

public:

    // Create an empty list
    LinkedList();

    // Insert a new route at the end of the list
    void insert(const std::string& route);

    // Display all routes
    void print();

    // Save the entire list into a file
    void saveToFile(const std::string& filename);

    // Append only new routes to a file
    void appendToFile(const std::string& filename);

    // Free dynamically allocated memory
    ~LinkedList();
};

#endif