from logic.utils import distance

# COMMENTS GENERATED BY IA SEARCHING ORDER ANS AGILITY.
# Counts how many search states were explored.
# Useful for measuring the cost of the algorithm.
nodes_explored = 0


def backtracking_route(base, asteroids, fuel):
    """
    Finds the optimal mining route using Backtracking.

    Objective:
    Maximize the total resource value collected while
    respecting fuel constraints and guaranteeing that
    the ship can always return to the base.

    Returns:
        best_route      -> optimal asteroid sequence
        best_value      -> maximum resources collected
        nodes_explored  -> number of explored states
    """

    global nodes_explored
    nodes_explored = 0

    # Best solution found so far
    best_route = []
    best_value = 0

    def backtrack(
        current,
        remaining,
        fuel_left,
        current_route,
        current_value
    ):
        """
        Recursive search function.

        Parameters:
            current        -> current position
            remaining      -> asteroids not yet visited
            fuel_left      -> remaining fuel
            current_route  -> route built so far
            current_value  -> resources collected so far
        """

        global nodes_explored

        # Count this search node
        nodes_explored += 1

        nonlocal best_route
        nonlocal best_value

        # ==================================================
        # PRUNING STEP
        # ==================================================
        #
        # Calculate the maximum value that could still be
        # obtained if every remaining asteroid were mined.
        #
        # This represents an optimistic upper bound.
        #
        # Example:
        # Current value = 300
        # Remaining asteroids = 100 + 150
        #
        # Maximum possible future value = 550
        #
        # If 550 is still worse than the current best
        # solution, there is no reason to continue
        # exploring this branch.
        #
        # This dramatically reduces the search space.
        # ==================================================

        remaining_value = sum(
            asteroid.value
            for asteroid in remaining
        )

        if current_value + remaining_value <= best_value:
            return

        # ==================================================
        # UPDATE BEST SOLUTION
        # ==================================================
        #
        # Whenever a route with higher value is found,
        # store it as the new optimal solution.
        #
        # The route is copied to avoid future recursive
        # modifications affecting the saved solution.
        # ==================================================

        if current_value > best_value:

            best_value = current_value

            best_route = current_route.copy()

        # ==================================================
        # EXPLORE NEXT POSSIBLE ASTEROIDS
        # ==================================================
        #
        # Try each remaining asteroid as the next move.
        #
        # Backtracking systematically explores all
        # feasible combinations.
        # ==================================================

        for asteroid in remaining:

            # Fuel required to reach this asteroid
            dist_to_asteroid = distance(
                current,
                asteroid
            )

            fuel_after_move = (
                fuel_left
                - dist_to_asteroid
            )

            # ------------------------------------------------
            # Constraint 1:
            # Ship cannot move if fuel becomes negative.
            # ------------------------------------------------

            if fuel_after_move < 0:
                continue

            # ------------------------------------------------
            # Constraint 2:
            # Ship must always be able to return safely
            # to the base.
            #
            # This prevents generating routes that become
            # impossible to finish.
            # ------------------------------------------------

            dist_back = distance(
                asteroid,
                base
            )

            if fuel_after_move < dist_back:
                continue

            # ------------------------------------------------
            # Build a new list excluding the asteroid that
            # is about to be visited.
            # ------------------------------------------------

            new_remaining = [
                a
                for a in remaining
                if a != asteroid
            ]

            # ------------------------------------------------
            # Recursive exploration
            #
            # The algorithm moves to the asteroid and
            # continues exploring deeper possibilities.
            # ------------------------------------------------

            backtrack(
                asteroid,
                new_remaining,
                fuel_after_move,
                current_route + [asteroid],
                current_value + asteroid.value
            )

    # ======================================================
    # INITIAL SEARCH
    # ======================================================
    #
    # Start from the base with:
    # - all asteroids available
    # - full fuel
    # - empty route
    # - zero collected value
    # ======================================================

    backtrack(
        base,
        asteroids,
        fuel,
        [],
        0
    )

    return (
        best_route,
        best_value,
        nodes_explored
    )